resources:
- operator.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: cockroach-operator
  newName: us.gcr.io/crdb-testing-282716/cockroach-operator
  newTag: 5efaab9
