apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "crdb.cockroachlabs.com/v1alpha1",
          "kind": "CrdbCluster",
          "metadata": {
            "name": "crdb-tls-example"
          },
          "spec": {
            "cockroachDBVersion": "v21.1.4",
            "dataStore": {
              "pvc": {
                "spec": {
                  "accessModes": [
                    "ReadWriteOnce"
                  ],
                  "resources": {
                    "requests": {
                      "storage": "10Gi"
                    }
                  },
                  "volumeMode": "Filesystem"
                }
              }
            },
            "nodes": 3,
            "tlsEnabled": true
          }
        }
      ]
    capabilities: Full Lifecycle
    categories: Database
    certified: "true"
    containerImage: registry.connect.redhat.com/cockroachdb/cockroachdb-operator:v1.7.14
    createdAt: "2021-07-06T11:51:10Z"
    description: CockroachDB Operator
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
    repository: https://github.com/cockroachdb/cockroach-operator
    support: Cockroach Labs
  name: cockroach-operator.v1.7.14
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CrdbCluster is the CRD for the cockroachDB clusters API
      displayName: CockroachDB Operator
      kind: CrdbCluster
      name: crdbclusters.crdb.cockroachlabs.com
      specDescriptors:
      - description: (Required) Database disk storage configuration
        displayName: Data Store
        path: dataStore
      - description: 'SupportsAutoResize marks that a PVC will resize without restarting
          the entire cluster Default: false'
        displayName: PVC Supports Auto Resizing
        path: dataStore.supportsAutoResize
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: (Required) Container image information
        displayName: Cockroach Database Image
        path: image
      - description: Number of nodes (pods) in the cluster
        displayName: Number of nodes
        path: nodes
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: (Optional) TLSEnabled determines if TLS is enabled for your CockroachDB
          Cluster
        displayName: TLS Enabled
        path: tlsEnabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      statusDescriptors:
      - description: OperatorStatus represent the status of the operator(Failed, Starting,
          Running or Other)
        displayName: OperatorStatus
        path: clusterStatus
      - description: List of conditions representing the current status of the cluster
          resource.
        displayName: Cluster Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      - description: CrdbContainerImage is the container that will be installed
        displayName: CrdbContainerImage
        path: crdbcontainerimage
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - displayName: Crdb Actions
        path: operatorActions
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: Database service version. Not populated and is just a placeholder
          currently.
        displayName: Version
        path: version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      version: v1alpha1
  description: This operator launches and manages a 3+ node cluster of CockroachDB.
  displayName: CockroachDB Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAA/xJREFUeNq0V9uLE1cY/85k08wk2TWyf8AGH30oI8kigrLxgsULbqC1PrR0Z3rRQh928yD2ySUKgvhg9lFFZ1ZhZR+kkdaCgiUrBSm7YYc+9KmF2AfBBzF46V6SOcfvTM7kvu5kM/1gcgIz53y/7/fdzkegSQK77y4roKhhJkMEFAgzfPgKcjnCFAv/LyhMzt8pRizoIkezq2o1wtKVQTpWGWRqJcpiuML6IAW+8qcaZda/Q8O73D0DrUeQEv6o7QcTgBguKf4QINNnkrZFw2TmxhPJ5O9PnlnXUNlkhTIVNhMGpbazGxLcPR+v/HGq1L5n/+jfqsKQGZDHkZW0QmSwIwCotFDZRvmaciyMOk8eGbiPq/X7l9EOpkbKL+PPYsOlrgC8yNeJtVhQCk7ZYZh2aUWFgNRnqwrL/XxJLvdyntQrgFvFEFcw0uXVSK/KtwRgIrFioB81hz4KGSAs47hWAu3Y+VXjfwXwefLVFANWU26Dbv4ayM3NBXOoXBcO1T65vDLVy5meY+B48rkqQ2iZp6YMH2WuFwdyze/Hz65OVcNw1Uk1he367Yew5SsDFJhRyyJWaFfO5f4VmTNRcL4JMMNXFxxI/oO013KcEjqzYYpLbEbwqu67/VbzDQAlbLJRR1j5Aw61GmBg0hcAe0b/Ul3rPUi86WR1z703at8A0OJ0S79ggQ0tIzaZbHUJpPsGgME3VgMCZo1lkj6dqHb4d/zsmoZ1wVVoCgBjfjDAmxDYYGclIE70EyIZ3+2ldRCffb/OlRuiPuToAGRFTKQ2O3/Aa7o8WhrhDSSDlZB3Ro0FwNCO2LA2jH2AirRjYD48pziVce/c2/7T8OPRYkrQX+9es0VFR8tqFCMI9LshyrL54IKsN5ir7Uk8ep3qOw3RDS0t+tqipDenHCov/HQ1pLelZMmPNCyLwOtIJxpg2QYA0lGcCKtfbMpbBvDnYsJquhG1tuXHgbz7f/5WMN9lu7OneHjI6tcFjgWHk8+8FiMYu/nOk/WeAGDqFYQbUl4BYNCkRBEp9A0AFS8IIBOeezyFCREHC34AyLuBmE6+iG/2/aGZ/+JuACKQfN8Ani7uLKFys/axNL0pYBumxWo+/XSw1DcA5yMmzQoA2hfJNxvGwpGLKylMSU3QP+vbfeDx0o5CnQUmGd8mKh1peeLcaqxeFdH6J19FC74BENbzGl9GIHEJm1GXVmyg1XHMgDKykPH9UsrlVPKVGmKhZT4ZUQXM9W1Mc2a/IWrizMfHM+dC+vBHxfJuWA8yv7TdQiZ0dw5oKrvunKD3onxLg4lZlE1CiN5S5TjtOCf8clE2ez2v59nQlW8O2mo1zIwqDqm46tgPrK2c816AAQCBW4SEJD8W2QAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - get
          - list
          - delete
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - statefulsets/finalizers
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - statefulsets/status
          verbs:
          - '*'
        - apiGroups:
          - certificates.k8s.io
          resources:
          - certificatesigningrequests
          verbs:
          - '*'
        - apiGroups:
          - certificates.k8s.io
          resources:
          - certificatesigningrequests/approval
          verbs:
          - '*'
        - apiGroups:
          - certificates.k8s.io
          resources:
          - certificatesigningrequests/status
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - services/finalizers
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - services/status
          verbs:
          - '*'
        - apiGroups:
          - crdb.cockroachlabs.com
          resources:
          - crdbclusters
          verbs:
          - '*'
        - apiGroups:
          - crdb.cockroachlabs.com
          resources:
          - crdbclusters/status
          verbs:
          - '*'
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - '*'
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets/finalizers
          verbs:
          - '*'
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets/status
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - nonroot
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: cockroach-operator-sa
      - rules:
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - anyuid
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: cockroach-database-sa
      deployments:
      - name: cockroach-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: cockroach-operator
          strategy: {}
          template:
            metadata:
              labels:
                app: cockroach-operator
            spec:
              containers:
              - args:
                - -feature-gates
                - Upgrade=false,ResizePVC=true
                - -zap-log-level
                - info
                env:
                - name: RELATED_IMAGE_COCKROACH_v20_1_4
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.1.4
                - name: RELATED_IMAGE_COCKROACH_v20_1_5
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.1.5
                - name: RELATED_IMAGE_COCKROACH_v20_1_8
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.1.8
                - name: RELATED_IMAGE_COCKROACH_v20_1_11
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.1.11
                - name: RELATED_IMAGE_COCKROACH_v20_1_12
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.1.12
                - name: RELATED_IMAGE_COCKROACH_v20_1_13
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.1.13
                - name: RELATED_IMAGE_COCKROACH_v20_1_14
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.1.14
                - name: RELATED_IMAGE_COCKROACH_v20_1_15
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.1.15
                - name: RELATED_IMAGE_COCKROACH_v20_1_16
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.1.16
                - name: RELATED_IMAGE_COCKROACH_v20_2_0
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.0
                - name: RELATED_IMAGE_COCKROACH_v20_2_1
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.1
                - name: RELATED_IMAGE_COCKROACH_v20_2_2
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.2
                - name: RELATED_IMAGE_COCKROACH_v20_2_3
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.3
                - name: RELATED_IMAGE_COCKROACH_v20_2_4
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.4
                - name: RELATED_IMAGE_COCKROACH_v20_2_5
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.5
                - name: RELATED_IMAGE_COCKROACH_v20_2_6
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.6
                - name: RELATED_IMAGE_COCKROACH_v20_2_7
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.7
                - name: RELATED_IMAGE_COCKROACH_v20_2_8
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.8
                - name: RELATED_IMAGE_COCKROACH_v20_2_9
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.9
                - name: RELATED_IMAGE_COCKROACH_v20_2_10
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v20.2.10
                - name: RELATED_IMAGE_COCKROACH_v21_1_0
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v21.1.0
                - name: RELATED_IMAGE_COCKROACH_v21_1_1
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v21.1.1
                - name: RELATED_IMAGE_COCKROACH_v21_1_2
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v21.1.2
                - name: RELATED_IMAGE_COCKROACH_v21_1_4
                  value: registry.connect.redhat.com/cockroachdb/cockroach:v21.1.4
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: cockroachdb
                image: registry.connect.redhat.com/cockroachdb/cockroachdb-operator:v1.7.14
                imagePullPolicy: IfNotPresent
                name: cockroach-operator
                resources:
                  requests:
                    cpu: 10m
                    memory: 32Mi
              serviceAccountName: cockroach-operator-sa
      permissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: cockroach-operator-sa
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - database
  - cockroachDB
  links:
  - name: Documentation
    url: https://docs.cockroachlabs.com
  - name: Operator Source
    url: https://github.com/cockroachdb/cockroach-operator
  - name: Cockroach Labs
    url: https://www.cockroachlabs.com
  maintainers:
  - email: support@cockroachlabs.com
    name: Cockroach Labs Support
  maturity: beta
  provider:
    name: Cockroach Labs
  version: 1.7.14
